### ISSUE TITLE
กรณีที่วันที่ DateTime เป็นค่า null API จะต้อง เป็น empty string แทนที่จะเป็น 0001-01-01 00:00:00 ใน api กลุ่ม customer

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#20]
ปัจจุบัน กรณี
"claimOpenDate": "0001-01-01 00:00:00",

ที่ต้องการ

"claimOpenDate": "",

**Comment by patiwat-w** [comment]
ทำเป็นตัวอย่าง เพื่อให้โตสทำต่อก็ได้นะน็อต

**Comment by noi2thiiz** [comment]
north: ลองหา solution ที่สามารถทำให้ obj Datetime ส่งค่า "" (empty string ได้)
p'tose: ถ้า north หาไม่ได้ใช้วิธีสร้าง 2 obj ใน model
