### ISSUE TITLE
reflector api ให้มาสร้างเป็น logicCommand ของ API ในกลุ่ม claim และ survey (ยังไม่ผ่าน)

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#24]
ตามรายการต่อไปนี้
AccidentPrilimSurveyorReportController
AssignedSurveyorController
ClaimRegistrationController
RequestSurveyorController
UpdateClaimInfoController
UpdateClaimNoController
UpdateSurveyStatusController

**Comment by noi2thiiz** [comment]
รอเทส

**Comment by patiwat-w** [comment]
ยังไม่ผ่าน และยัง deploy QA ไม่สำเร็จ
