### ISSUE TITLE
update ซ่อมรายการนี้  (api updateClaimInfo)

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#29]
update ซ่อมรายการนี้  เนื่องจาก อนุมัติแล้วปรับยอดแล้ว (Adjusted)  แล้ว  คือจบกระบวนการแล้ว
หากเป็น status อื่น ต้องตรวจสอบข้อมูลก่อน
{
  "claimNo": "V0663445",
  "highLossCaseFlag": "N",
  "ticketNo": "CAS201707-06638",
  "claimNotiNo": "1707-05570",
  "legalCaseFlag": "N",
  "vipCaseFlag": "N",
  "claimStatusCode": "4",
  "claimStatusDesc": "อนุมัติแล้วปรับยอดแล้ว (Adjusted)"
}

{
  "claimNo": "C0106397",
  "highLossCaseFlag": "N",
  "ticketNo": "CAS201707-07858",
  "claimNotiNo": "1707-06580",
  "legalCaseFlag": "N",
  "vipCaseFlag": "N",
  "claimStatusCode": "4",
  "claimStatusDesc": "อนุมัติแล้วปรับยอดแล้ว (Adjusted)"
}

{
  "claimNo": "V0664750",
  "highLossCaseFlag": "N",
  "ticketNo": "CAS201707-08262",
  "claimNotiNo": "1707-06924",
  "legalCaseFlag": "N",
  "vipCaseFlag": "N",
  "claimStatusCode": "4",
  "claimStatusDesc": "อนุมัติแล้วปรับยอดแล้ว (Adjusted)"
}

กรณีเป็น 0 สามารถซ่อมได้ เป็นการยกเลิก
{
  "claimNo": "V0666492",
  "highLossCaseFlag": "N",
  "ticketNo": "CAS201708-00584",
  "claimNotiNo": "1708-00498",
  "legalCaseFlag": "N",
  "vipCaseFlag": "N",
  "claimStatusCode": "0",
  "claimStatusDesc": "ปิด (Closed)"
}

{
  "claimNo": "V0666492",
  "highLossCaseFlag": "N",
  "ticketNo": "CAS201708-00584",
  "claimNotiNo": "1708-00498",
  "legalCaseFlag": "N",
  "vipCaseFlag": "N",
  "claimStatusCode": "4",
  "claimStatusDesc": "อนุมัติแล้วปรับยอดแล้ว (Adjusted)"
}

**Comment by noi2thiiz** [comment]
ทำแล้วแต่ติด case resolved เลยไม่สามารถ update ได้
