### ISSUE TITLE
CRM_RegLead (ทดสอบไม่ผ่าน) 

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#3]
สำหรับ เฟส2

**Comment by patiwat-w** [comment]
- ใส่จุดทศนิยมแล้ว error ในฟิลด์   "budgetAmount":  เช่น  1000.00    ต้องสามารถใส่จุดทศนิยมได้เนื่องจากค่าเงิน
- ค่า บางค่า เป็น optional ไม่จำเป็นต้องใส่ก็ได้ หากไม่ส่ง JSON มา ให้ถือว่าไม่ต้องดำเนินการใด ๆ กับ field นั้น เช่น companyInfo เป็น optional

**Comment by patiwat-w** [comment]
เพิ่มเติม
- "insuredIssueDate": ""    เป็น optional ส่งค่า "" , null , หรือ ไม่ส่ง field  มาก็ได้  ให้เช็คก่อน map ค่า
- mobilePhone , insuredMobilePhone เป็นตัวเลข (string ) ไม่เกิน 10 หลัก ไม่มีเครื่องหมายใดๆ

**Comment by patiwat-w** [comment]
ผลทดสอบ
(ผ่าน) ใส่จุดทศนิยมแล้ว error ในฟิลด์ "budgetAmount": เช่น 1000.00 ต้องสามารถใส่จุดทศนิยมได้เนื่องจากค่าเงิน
(ผ่าน) "insuredIssueDate": "" เป็น optional ส่งค่า "" , null , หรือ ไม่ส่ง field มาก็ได้ ให้เช็คก่อน map ค่า
(ผ่าน) mobilePhone , insuredMobilePhone เป็นตัวเลข (string ) ไม่เกิน 10 หลัก ไม่มีเครื่องหมายใดๆ

(ไม่ผ่าน) กรณีที่ไม่ระบุ  productInfo.categoryName , productInfo.budgetAmount จะเกิด error 500 2 field นี้เป็น Optional ไม่ต้องระบุก็ได้ 

(ไม่ผ่าน) leadid ที่ return เป็นคนละตัวกับที่ สร้างใหม่ 

 ในโค้ดนี้
 var query = from c in svcContext.LeadSet
                            where c.FirstName == contentModel.contactInfo.firstName && c.LastName == contentModel.contactInfo.lastName && c.Subject == contentModel.generalHeader.topic
                            select c;
ขอให้ใช้ Guid แทน เพราะมีโอกาศที่จะไปเจอ lead อื่นที่ ชื่อ นามสกุลซ้ำกัน

**Comment by patiwat-w** [comment]
กดผิด

**Comment by noi2thiiz** [comment]
รอเรื่อง permission สำหรับการ set ค่า address จาก input ให้ field Address1_Composite

**Comment by noi2thiiz** [comment]
** Reminder **
รอเรื่อง permission สำหรับการ set ค่า address จาก input ให้ field Address1_Composite
