### ISSUE TITLE
API สำหรับ Execute SQL

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#35]
พัฒนา API ง่าย ๆ สำหรับ Execute SQL
เพื่อเอาไว้ใช้ support เวลาที่เราไม่ได้อยู่ที่เทเวศ
สร้างในเฟส2

input
    database name
     sql command

output 
      execute  result (dynamic ได้อะไรก็เอามาโยนเป็น output เลย )

**Comment by noi2thiiz** [comment]
URL Endpoint: https://crmappdev.deves.co.th/proxy/xml.ashx?http://192.168.8.121/QueryAPI/api/QuerySQL

**ตัวอย่าง Input**
{
	"databaseName": "CRM_CUSTOM_APP_PRO",
	"sqlCommand": "SELECT TOP 10 * FROM XrmApiTransactionLog ORDER BY Id DESC;"
}

value สำหรับ database แต่ละตัว
- CRMDB on QA -> "CRMQA_MSCRM"
- CRM_CUSTOMAPP on QA -> "CRM_CUSTOM_APP"
- CRMDB on Production -> "CRM_MSCRM"
- CRM_CUSTOMAPP on Production ->"CRM_CUSTOM_APP_PRO"
