### ISSUE TITLE
CRM_RegOpportunityPerson (ทดสอบยังไม่ผ่าน)

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#4]
เฟส2

**Comment by patiwat-w** [comment]
- ตรวจสอบ field ที่เป็นค่าเงิน
- ระบบุ leadId  แล้วต้องไป qualify lead ให้ด้วย
- input ต้องรวม (inherit) ส่วนของ RegClientPersonal  มาด้วยเพื่อไปสร้าง Client ใน CLS โดยใช้งาน buzCRMRegClientPersonal
- mobilePhone   ต้องไม่รับ อักขระอื่นๆนอกจากตัวเลข

**Comment by noi2thiiz** [comment]
- Schema 
	= ขยาย size country 
- buz
	= สร้างคนได้แล้ว เหลือ mapping field
