### ISSUE TITLE
Apply SQLQueryStrategy to API Customer Portal 

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#63]
- เอา sql Strategy ไปใช้กับ api customer portal ของโตสเพื่อให้สามารถทดสอบจาก debug mode ได้ ซึ่ง API จะมี 4 ตัวดังนี้

1.  InquiryCustomerCaseController
2. InquiryCustomerClaimController
3. InquiryCustomerController
4. InquiryCustomerPolicyController

- create branch from "integrate-dev-tose"
- เมื่อทำเสร็จแล้ว ให้ สร้าง pull request เลือก base branche เป็น  "integrate-dev-tose"   (แตกจาก branche ให้ กลับมา branches นั้น) และกำหนด reviewer เป็น โตส และ พี่   และ Assignee เป็น พี่ 

input ที่จะใช้ทดสอบ ดูได้จากหน้า swagger   มี example input ไว้แล้ว

**Comment by noi2thiiz** [comment]
CRM_InquiryCustomer
{
	"generalHeader" :
	{
		"requester" : "WEB"	
	},
	"conditions":
	{
		"fullName": "",
		"idCard": "",
		"phoneNumber": "",
    	"cleansingId":"",
    	"crmClientId": "",
    	"email": "",
    	"customerType":"C"
	}
}

CRM_InquiryCustomerCase
{
	"generalHeader" :
	{
		"requester" : "WEB"	
	},
	"conditions":
	{
		"cleansingId": "",
		"ticketNo":"CAS201705-02002"
	}
}



CRM_InquiryCustomerClaim
{
	"generalHeader" :
	{
		"requester" : "WEB"	
	},
	"conditions":
	{
		"cleansingId" : "",
		"claimNotiNo" : "",
    	"claimNo" : "CL001",
    	"policyNo" : "",
    	"policyCarRegisterNo" : "",
    	"parentPolicyId" : ""
	}
}



CRM_InquiryCustomerPolicy
{
	"generalHeader" :
	{
		"requester" : "WEB"	
	},
	"conditions":
	{
		"crmClientId": "",
    	"cleansingId": "C2017-002204164",
    	"policyCarRegisterNo": "",
    	"policyNo": "",
    	"chassisNo":""
	}
}
