### ISSUE TITLE
CRM_InquiryOpportunity

### ISSUE THREAD

**Issue by patiwat-w** [primefactorgit/DEVES.IntegrationAPI#88]

**Comment by noi2thiiz** [comment]
InquiryOpp
- Schema 
	= ขยาย size OppId ชั่วคราวเพื่อ test Guid
- Output model
	= แก้ type int -> decimal ของ price กับ budgetAmount
- buz
	= สามารถ inquiry ได้แล้ว เหลือ mapping field
